version: '2'
services:
  pop3_proxy:
    build:
      context: ./tcp-proxy
      args:
        http_proxy:
        https_proxy:
    links:
      - vpn:vpn_http_proxy
    restart: always
    environment:
      proxy_target: "${POP3_PROXY_TARGET}"
    ports:
      - "${POP3_BIND_IP_PORT}:3000"

  smtp_proxy:
    build:
      context: ./tcp-proxy
      args:
        http_proxy:
        https_proxy:
    links:
      - vpn:vpn_http_proxy
    restart: always
    environment:
      proxy_target: "${SMTP_PROXY_TARGET}"
    ports:
      - "${SMTP_BIND_IP_PORT}:3000"
