version: '2'
services:
  vpn:
    build:
      context: ./openvpn
      args:
      - http_proxy=${http_proxy}
    volumes:
      - ./vpn-config:/etc/vpn-config
    ports:
      - "${PROXY_BIND_IP_PORT}:8080"
    tty: true
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    restart: always
