version: '2'
services:
  pop3_proxy:
    build:
      context: ./pop3-proxy
    environment:
      - proxy_target=${POP3_PROXY_TARGET}
    links:
      - vpn:vpn_http_proxy
    ports:
      - "${POP3_BIND_IP_PORT}:110"
    tty: true
    restart: always
