version: '2'

x-tcp_proxy: &proxy_base
  build:
    context: ./tcp-proxy
    args:
      http_proxy:
      https_proxy:
  environment: &proxy_environment_base
    proxy_host: "vpn"
    proxy_port: 8080
  restart: always

services:
  vpn:
    build:
      context: ./openvpn
      args:
        http_proxy:
        https_proxy:
    volumes:
      - ./vpn-config:/etc/vpn-config
    ports:
      - "${PROXY_BIND_IP_PORT}:8080"
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    environment:
      TZ:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"

  pop3_proxy:
    <<: *proxy_base
    profiles:
      - mail
    environment:
      <<: *proxy_environment_base
      proxy_target: "${POP3_PROXY_TARGET}"
    ports:
      - "${POP3_BIND_IP_PORT}:3000"

  smtp_proxy:
    <<: *proxy_base
    profiles:
      - mail
    environment:
      <<: *proxy_environment_base
      proxy_target: "${SMTP_PROXY_TARGET}"
    ports:
      - "${SMTP_BIND_IP_PORT}:3000"
