version: '2'
services:
  vpn:
    build:
      context: ./openvpn
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./vpn-config:/etc/vpn-config
    ports:
      - "${PROXY_BIND_IP_PORT}:8080"
    tty: true
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    environment:
      - TZ
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
