version: '2'
services:
  pop3_proxy:
    build:
      context: ./tcp-proxy
      args:
        - http_proxy
        - https_proxy
    environment:
      - proxy_target=${POP3_PROXY_TARGET}
    links:
      - vpn:vpn_http_proxy
    ports:
      - "${POP3_BIND_IP_PORT}:3000"
    tty: true
    restart: always

  smtp_proxy:
    build:
      context: ./tcp-proxy
      args:
        - http_proxy
        - https_proxy
    environment:
      - proxy_target=${SMTP_PROXY_TARGET}
    links:
      - vpn:vpn_http_proxy
    ports:
      - "${SMTP_BIND_IP_PORT}:3000"
    tty: true
    restart: always
